import { redirect, notFound } from "next/navigation";
import Link from "next/link";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { hasAdminAccess } from "@/lib/permissions";

const definitions = {
  roles: { label: "Role", model: "role", fields: ["name", "description"] },
  users: { label: "User", model: "user", fields: ["name", "username", "email", "password", "role"] },
  students: { label: "Murid", model: "student", fields: ["name", "birthDate", "phone", "parentName", "parentPhone", "classLabel"] },
  reflections: { label: "Renungan", model: "reflection", fields: ["title", "content", "date", "bibleVerse"] },
  "reading-tracks": { label: "Reading Track", model: "readingTrack", fields: [] },
  attendances: { label: "Kehadiran", model: "attendance", fields: ["studentId", "date", "status", "classLabel", "presentCount", "totalCount"] },
  finances: { label: "Keuangan", model: "finance", fields: ["type", "description", "amount", "date", "category", "notes"] },
  activities: { label: "Kegiatan", model: "activity", fields: ["title", "date", "startTime", "endTime", "location", "category", "description"] },
} as const;
type ModuleName = keyof typeof definitions;

export default async function AdminModulePage({ params, searchParams }: { params: Promise<{ module: string }>; searchParams: Promise<{ month?: string }> }) {
  const user = await getCurrentUser();
  const { module } = await params;
  if (!(module in definitions)) notFound();
  if (!user || !hasAdminAccess(user.role?.name)) redirect("/dashboard");
  const definition = definitions[module as ModuleName];
  if (module === "attendances") {
    const month = (await searchParams).month ?? "";
    const selectedMonth = /^\d{4}-\d{2}$/.test(month) ? month : new Date().toISOString().slice(0, 7);
    const startDate = new Date(`${selectedMonth}-01T00:00:00.000Z`);
    const endDate = new Date(startDate);
    endDate.setUTCMonth(endDate.getUTCMonth() + 1);
    const attendanceRows = await prisma.attendance.findMany({ where: { date: { gte: startDate, lt: endDate }, status: "hadir" }, include: { student: { include: { user: true } } }, orderBy: [{ date: "desc" }, { studentId: "asc" }] });
    const dates = new Map<string, typeof attendanceRows>();
    attendanceRows.forEach((row) => { const key = row.date.toISOString().slice(0, 10); dates.set(key, [...(dates.get(key) ?? []), row]); });
    const weeks = new Map<string, Map<string, typeof attendanceRows>>();
    dates.forEach((rows, dateKey) => { const date = new Date(`${dateKey}T00:00:00.000Z`); const sunday = new Date(date); sunday.setUTCDate(date.getUTCDate() - date.getUTCDay()); const weekKey = sunday.toISOString().slice(0, 10); weeks.set(weekKey, new Map([...(weeks.get(weekKey) ?? new Map()), [dateKey, rows]])); });
    const groupName = (label: string | null | undefined) => { const normalized = (label ?? "").toLowerCase(); if (normalized.includes("remaja")) return "Remaja"; if (normalized.includes("sedang")) return "Sedang"; return "Kecil"; };
    return <main className="dashboard-shell"><header className="dashboard-header"><div><p className="eyebrow">Panel Admin</p><h1>Kelola Kehadiran</h1><p>Pilih minggu dan tanggal untuk melihat murid yang hadir berdasarkan tingkat kelas.</p></div><div className="header-actions-row"><Link className="back-link" href="/dashboard">Beranda</Link><Link className="back-link" href="/admin">Semua modul</Link></div></header><form className="filter-form attendance-filter" method="get"><label>Bulan<input type="month" name="month" defaultValue={selectedMonth} /></label><button type="submit">Tampilkan</button></form><section className="attendance-weeks">{weeks.size ? Array.from(weeks.entries()).map(([weekKey, weekDates]) => <details className="attendance-week" key={weekKey} open><summary>Minggu, {new Date(`${weekKey}T00:00:00.000Z`).toLocaleDateString("id-ID", { day: "numeric", month: "long", year: "numeric" })}</summary><div className="attendance-dates">{Array.from(weekDates.entries()).map(([dateKey, rows]) => { const groups = { Kecil: rows.filter((row) => groupName(row.student?.classLabel) === "Kecil"), Sedang: rows.filter((row) => groupName(row.student?.classLabel) === "Sedang"), Remaja: rows.filter((row) => groupName(row.student?.classLabel) === "Remaja") }; return <details className="attendance-date" key={dateKey}><summary>{new Date(`${dateKey}T00:00:00.000Z`).toLocaleDateString("id-ID", { weekday: "long", day: "numeric", month: "long", year: "numeric" })}</summary><div className="attendance-groups">{Object.entries(groups).map(([name, group]) => <div className="attendance-group" key={name}><h3>Kelas {name}</h3>{group.length ? <ol>{group.map((row) => <li key={row.id}>{row.student?.user.name ?? "Nama murid belum tersedia"}</li>)}</ol> : <p>Belum ada murid hadir.</p>}</div>)}</div></details>; })}</div></details>) : <section className="empty-state"><strong>Belum ada data kehadiran</strong><span>Tidak ada catatan hadir pada bulan yang dipilih.</span></section>}</section></main>;
  }
  if (module === "reading-tracks") {
    const tracks = await prisma.readingTrack.findMany({ include: { student: { include: { user: true } }, reflection: true }, orderBy: { updatedAt: "desc" }, take: 200 });
    return <main className="dashboard-shell"><header className="dashboard-header"><div><p className="eyebrow">Panel Admin</p><h1>Reading Track</h1><p>Laporan durasi dan progres murid. Modul ini hanya untuk melihat data.</p></div><div className="header-actions-row"><Link className="back-link" href="/dashboard">Beranda</Link><Link className="back-link" href="/admin">Semua modul</Link></div></header><section className="record-list reading-list">{tracks.length ? tracks.map((track) => <div className="record-row" key={track.id}><span><strong>{track.student.user.name}</strong><small>{track.reflection.title}</small></span><span>{track.duration} detik {track.completed ? "• Selesai" : "• Berjalan"}</span></div>) : <p>Belum ada aktivitas membaca.</p>}</section></main>;
  }
  const records = await (prisma as unknown as Record<string, { findMany: (args: object) => Promise<Record<string, unknown>[]> }>)[definition.model].findMany({ take: 100, orderBy: { id: "desc" }, ...(module === "students" ? { include: { user: true } } : {}), ...(module === "reflections" ? { include: { creator: true } } : {}), ...(module === "finances" ? { include: { recorder: true } } : {}) });
  const optional = ["description", "password", "bibleVerse", "classLabel", "parentName", "parentPhone", "phone", "category", "notes", "startTime", "endTime"];
  const labels: Record<string, string> = { role: "Peran", name: "Nama", username: "Username", email: "Email", password: "Password", birthDate: "Tanggal lahir", phone: "No. telepon", parentName: "Nama orang tua", parentPhone: "No. telepon orang tua", classLabel: "Kelas", content: "Konten renungan", status: "Status", type: "Jenis transaksi" };
  return <main className="dashboard-shell"><header className="dashboard-header"><div><p className="eyebrow">Panel Admin</p><h1>Kelola {definition.label}</h1><p>Tambah, ubah, dan hapus data langsung dari database MySQL.</p></div><div className="header-actions-row"><Link className="back-link" href="/dashboard">Beranda</Link><Link className="back-link" href="/admin">Semua modul</Link></div></header><section className="crud-panel"><form className="crud-form" action={`/api/admin/${module}`} method="post">{definition.fields.map((field) => <label className={field === "content" ? "wide-field" : ""} key={field}>{labels[field] ?? field}{field === "role" ? <select name={field} defaultValue="guru"><option value="admin">Administrator</option><option value="guru">Guru</option><option value="sekretaris">Sekretaris</option><option value="bendahara">Bendahara</option><option value="murid">Murid</option></select> : field === "status" ? <select name={field} defaultValue="hadir"><option value="hadir">Hadir</option><option value="izin">Izin</option><option value="sakit">Sakit</option><option value="alpa">Alpa</option></select> : field === "type" ? <select name={field} defaultValue="pemasukan"><option value="pemasukan">Pemasukan</option><option value="pengeluaran">Pengeluaran</option></select> : field === "classLabel" ? <select name={field} defaultValue="Kecil"><option value="Kecil">Kelas Kecil</option><option value="Sedang">Kelas Sedang</option><option value="Remaja">Kelas Remaja</option></select> : field === "content" || field === "description" || field === "notes" ? <textarea name={field} rows={field === "content" ? 12 : 4} required={!optional.includes(field)} /> : <input name={field} type={field === "password" ? "password" : field === "date" || field === "birthDate" ? "date" : "text"} required={!optional.includes(field)} />}</label>)}<button type="submit">Tambah data</button></form><div className="record-list">{records.length === 0 ? <p>Belum ada data.</p> : records.map((record) => <div className="record-row" key={String(record.id)}><span>#{String(record.id)} {String((record.user as { name?: string } | undefined)?.name ?? record.name ?? record.title ?? record.description ?? record.status ?? "Data")} {module === "reflections" && <small>Oleh: {String((record.creator as { name?: string } | undefined)?.name ?? "-")}</small>}</span><span className="record-actions"><Link href={`/admin/${module}/edit/${String(record.id)}`}>Edit</Link><form action={`/api/admin/${module}?id=${String(record.id)}`} method="post"><input type="hidden" name="_method" value="DELETE" /><button className="delete-button">Hapus</button></form></span></div>)}</div></section></main>;
}
